AirlineMS/Models/Entities/Branch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AirlineMS.Models.Entities
{
    public class Branch : BaseEntity
    {
        public string Name {get; set;}
        public string CompanyId {get; set;}
        public Company Company{get; set;}
        public string Email {get; set;}
        public string Address {get; set;}
        public string PhoneNumber {get; set;}
        public List<Staff> Staffs {get; set;}






    }
}

AirlineMS/Controllers/BranchController.cs
using AirlineMS.Models.Dtos;
using AirlineMS.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AirlineMS.Controllers
{
    public class BranchController : Controller
    {
        private readonly IBranchService _branchService;

        public BranchController(IBranchService branchService)
        {
            _branchService = branchService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateBranchRequestModel model)
        {
            var response = _branchService.Create(model);
            if (response.Status)
            {
                TempData["Successful"] = " Created Successful";

                return RedirectToAction("List", new {id = response.Data.Id});
            }
            return View();
        }

        [HttpGet]
        public IActionResult CreateHead()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateHead(string id, CreateHeadRequestModel model)
        {
            var response = _branchService.CreateHeadquarters(id, model);
            if (response.Status)
            {
                TempData["Successful"] = " Created Successful";
                return RedirectToAction("List", new {id = id});
            }
            TempData["error"] = response.Message;
            return View();
        }

        [HttpGet]
        public IActionResult Delete(string id)
        {
            // var response = _branchService.Get(id);
            return View();
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult RealDelete(string id)
        {
            var response = _branchService.Delete(id);
            if (response.Status)
            {
                TempData["Successful"] = "Deleted successfully";

                return RedirectToAction("List");
            }
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult List(string id)
        {
            var response = _branchService.GetBranchesByCompanyId(id);
            return View(response.Data);
        }

        [HttpGet]
        public IActionResult Update(string id)
        {
            // var response = _branchService.Get(id);
            return View();
        }

        [HttpPost]
        public IActionResult Update(string id, UpDateBranchRequestModel model)
        {
            var response = _branchService.Update(id, model);
            if (response.Status)
            {
                TempData["Successful"] = " Updated Successful";

                return RedirectToAction("List");
            }
            return View();
        }
    }
}

AirlineMS/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AirlineMS.Models.Dtos;
using AirlineMS.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace AirlineMS.Controllers
{
    public class StaffController : Controller
    {
        private readonly IStaffService _staffService;
        public StaffController(IStaffService staffService)
        {
            _staffService = staffService;
        }

        [HttpGet, ActionName("List")]
        public IActionResult ListOfStaffsByBranch(string branchId)
        {
           var staffs = _staffService.GetStaffsByBranchId(branchId);
           return View(staffs.Data);
        }
        public IActionResult ListOfStaffsByCompany(string companyId)
        {
           var staffs= _staffService.GetStaffsByCompanyId(companyId);
           return View(staffs.Data);
        }

        public IActionResult Details(string id)
        {
            var staff= _staffService.Get(id);
            return View(staff.Data);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(string branchId, CreateStaffRequestModel model)
        {
            var staff = _staffService.Create(branchId, model);
            if(staff is not null)
            {
                TempData["Exist"] = "Staff created Successfully";
                return RedirectToAction("List");
            }
            return View(); 
        }
        [HttpGet]
        public IActionResult Update(string id)
        {
            var staff = _staffService.Get(id);
            var updateModel  = new UpdateStaffRequestModel
            {
                FirstName = staff.Data.FirstName,
                LastName = staff.Data.LastName,
                PhoneNumber = staff.Data.PhoneNumber

            };
            return View(updateModel);
        }
        [HttpPost]
        public IActionResult Update(string id,UpdateStaffRequestModel model)
        {
            
            _staffService.Update(id,model);
            return RedirectToAction("ListOfStaffsByCompany");
        }
        [HttpGet]
        public IActionResult Delete(string id)
        {
           var staff = _staffService.Get(id);
            return View(staff.Data);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult ActualDelete(string id)
        {
            
            return View();
        }


    }
}

AirlineMS/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AirlineMS.Models.Dtos;
using AirlineMS.Services.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace AirlineMS.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        [HttpGet]
        public IActionResult Login()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginUserRequestModel model)
        {
            var user = _userService.Login(model);
            if (user != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.NameIdentifier, user.Data.Id),
                    new Claim(ClaimTypes.Email, user.Data.Email),
                    new Claim(ClaimTypes.Name, user.Data.FirstName +" "+ user.Data.LastName),
                    new Claim(ClaimTypes.HomePhone, user.Data.PhoneNumber)
                };

                var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var claimsPrincipal = new ClaimsPrincipal(claimIdentity);

                HttpContext.SignInAsync(claimsPrincipal);
                if(user.Status == true)
                {
                    if(user.Data.Roles.Select(r => r.Name).Contains("super admin"))
                    {
                        return RedirectToAction("Super");
                    }
                    else if(user.Data.Roles.Select(r => r.Name).Contains("Company Manager"))
                    {
                        return RedirectToAction("Manager");
                    }
                }

                
            }
            return View();


        }

        public IActionResult List()
        {
            var users = _userService.GetAll();
            return View(users.Data);
        }

        public IActionResult Super()
        {
            return View();
        }

        [HttpGet]
        [ActionName("Manager")]
        public IActionResult CompanyManager()
        {
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }


        
        /* [ChildActionOnly]
        public ActionResult GetHtmlPage(string path)
        {
            return new FilePathResult(path, "text/html");
            
        } */

    }
}

AirlineMS/Views/Branch/Create.cshtml
@using AirlineMS.Models.Dtos
@model CreateBranchRequestModel
@{
    ViewData["Title"] = "Create Branch";
}
<div class="border p-3 mt-4">
    <div class="text-center"><h1>@ViewData["Title"]</h1></div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <form asp-action="Create">
                <div>
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" type="text" />
                </div>
                <div>
                    <label asp-for="PhoneNumber"></label>
                    <input asp-for="PhoneNumber" class="form-control" type="text" />
                </div>
                <div>
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" type="text" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div>
                    <label asp-for="Address"></label>
                    <input asp-for="Address" class="form-control" type="text" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="mt-2 text-end">
                    <button type="submit" class="btn btn-primary" style="width: 30%">Create Branch</button>
                </div>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div> 

AirlineMS/Views/Branch/CreateHead.cshtml
@using AirlineMS.Models.Dtos
@model CreateHeadRequestModel
@{
    ViewData["Title"] = "Create Headquater";
}
<div class="border p-3 mt-4">
    <div class="text-center"><h1>@ViewData["Title"]</h1></div>
    <div class="text-center text-danger">
        @if (TempData["error"] != null)
        {
            @TempData["error"];
        }
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <form asp-action="CreateHead">
                <div>
                    <label asp-for="PhoneNumber"></label>
                    <input asp-for="PhoneNumber" class="form-control" type="text" />
                </div>
                <div>
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" type="email" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div>
                    <label asp-for="Address"></label>
                    <input asp-for="Address" class="form-control" type="text" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="mt-2 text-end">
                    <button type="submit" class="btn btn-primary" style="width: 30%">Create Branch</button>
                </div>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div> 

AirlineMS/Views/Branch/Delete.cshtml
@using AirlineMS.Models.Dtos;
@model BranchDto;
@{
    ViewData["Title"] = "Delete Branch";
}

<div class="border mt-4">
    <div class="col-lg-12"><center><h1>@ViewData["Title"]</h1></center></div>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <div class=""><center>Are you sure you want to delete this Branch?</center></div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <td><strong>Id</strong></td>
                        <td>@Model.Id</td>
                    </tr>
                    <tr>
                        <td><strong>Branch Name</strong></td>
                        <td>@Model.Name</td>
                    </tr>
                    <tr>
                    <tr>
                        <td><strong>Branch Email</strong></td>
                        <td>@Model.Email</td>
                    </tr>
                    <tr>
                        <td><strong>Branch PhoneNumber</strong></td>
                        <td>@Model.PhoneNumber</td>
                    </tr>
                    <tr>
                        <td><strong>Address</strong></td>
                        <td>@Model.Address</td>
                    </tr>
                </tbody>
            </table>
            <div class="text-end">
                <form asp-action="Delete">
                    <input type="hidden" name="id" value="@Model.Id" />
                    <button type="submit" class="btn btn-danger" style="width: 30%;">Delete Branch</button>
                </form>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

AirlineMS/Views/Branch/Index.cshtml
@using AirlineMS.Models.Dtos
@model BranchManagerDto
@{
    ViewData["Title"] = "Branch Manager Dashboard";
}
<div class="">
    <div class="row">
        <div class="col-md-2 border" style="min-height: 520px; padding: 0px; margin: 0px">
            @await Html.PartialAsync("~/Views/Branch/Menu.cshtml")
        </div>
        <div class="row col-md-10 pt-3">
            <div class="col-md-12 text-center">
                <h3>@ViewData["Title"]</h3>
            </div>
            <div class="col-md-12">
                
            </div>
        </div>
    </div>
</div>

AirlineMS/Views/Branch/List.cshtml
@using AirlineMS.Models.Dtos
@model IEnumerable<BranchDto>
@{
    ViewData["Title"] = "Branch List";
}
<div>
    <div class="text-center">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone Number</th>
                        <th>Address</th>
                        <th>Update</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var branch in Model)
                    {
                        <tr>
                            <td>@branch.Id</td>
                            <td>@branch.Name</td>
                            <td>@branch.Email</td>
                            <td>@branch.PhoneNumber</td>
                            <td>@branch.Address</td>
                            <td>
                                <a asp-controller="CompanyManager" asp-action="Add">Create Manager</a>
                            </td>
                            <td>
                                <a asp-controller="Branch" asp-action="Delete" asp-route-id="@branch.Id">Remove</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-lg-2"></div>
    </div>
</div>

AirlineMS/Views/Branch/Menu.cshtml
<a class="dropdown-item active" asp-action="Branch" asp-controller="User">Dashboard</a>
<a class="dropdown-item" asp-action="Add" asp-controller="Staff">Add Staff</a>
<a class="dropdown-item" asp-action="List" asp-controller="Staff">Staff List</a>
<a class="dropdown-item" asp-action="List" asp-controller="Passenger">Passenger List</a>

AirlineMS/Views/Branch/Update.cshtml
@using AirlineMS.Models.Dtos
@model BranchDto
@{
    ViewData["Title"] = "Update Branch";
}
<div>
    <div class="text-center">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form asp-controller="Branch" asp-action="Update" asp-route-Id="@Model.Id">
                <div>
                    <label for="Name">Name</label>
                    <input type="text" name="Name" value="@Model.Name"/>
                </div>
                <div>
                    <label for="PhoneNumber">PhoneNumber</label>
                    <input type="text" name="PhoneNumber" value="@Model.PhoneNumber"/>
                </div>
                <div>
                    <label for="Address">Address</label>
                    <input type="text" name="Address" value="@Model.Address"/>
                </div>
                <div>
                    <button class="btn btn-primary" style="width: 30%;">Update Branch</button>
                </div>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>