AirlineMS/Models/Entities/Aircraft.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AirlineMS.Models.Entities
{
    public class Aircraft : BaseEntity
    {
        public string Name{get; set;}
        public string EngineNumber{get; set;}
        public int Capacity{get; set;}
        public string CompanyId{get; set;}
        public Company Company{get; set;}
        public ICollection<Flight> Flights = new HashSet<Flight>();
    }
}

AirlineMS/Controllers/AircraftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AirlineMS.Models.Dtos;
using AirlineMS.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AirlineMS.Controllers
{
    public class AircraftController : Controller
    {
         private readonly IAircraftService _aircraftService;

        public AircraftController(IAircraftService aircraftService)
        {
            _aircraftService = aircraftService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(string companyId, CreateAircraftRequestModel model)
        {
            var response = _aircraftService.Create(companyId, model);
            if (response.Status)
            {
                TempData["Successful"] = "Created Successful";

                return RedirectToAction("List");
            }
            return View();
        }


        [HttpGet]
        public IActionResult Delete(string id)
        {
            return View();
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult RealDelete(string companyId)
        {
            var response = _aircraftService.Delete(companyId);
            if (response.Status)
            {
                TempData["Successful"] = " Deleted Successful";

                return RedirectToAction("List");
            }
            return View();
        }

        [HttpGet]
        public IActionResult List(string id)
        {
            var response = _aircraftService.GetAircraftsByCompanyId(id);
            return View(response.Data);
        }

        public IActionResult Details(string id)
        {
            var response = _aircraftService.GetAircraftByCompanyId(id);
            return View(response.Data);
        }
       
        [HttpGet]
        public IActionResult Update(string id)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Update(string id, UpdateAircraftRequestModel model)
        {
            var response = _aircraftService.Update(id, model);
            if (response.Status)
            {
                TempData["Successful"] = " Updated Successful";

                return RedirectToAction("List");
            }
            return View();
        }
    }
}

AirlineMS/Views/Aircraft/Create.cshtml
@{
    ViewData["Title"] = "Create Aircraft";
}
<div>
    <div class="text-center">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form asp-controller="Aircraft" asp-action="Create" asp-route-agencyId="">
                <div name="padding: ">
                    <label for="">Name</label>
                    <input type="" name="Name"/>
                </div>
                <div>
                    <label for="">Engine Number</label>
                    <input type="" name="EngineNumber"/>
                </div>
                <div>
                    <label for="">Capacity</label>
                    <input type="" name="Capacity"/>
                </div>
                <div>
                    <button class="btn btn-primary">Create Aircraft</button>
                </div>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

AirlineMS/Views/Aircraft/Delete.cshtml
@using AirlineMS.Models.Dtos;
@model AircraftDto;
@{
    ViewData["Title"] = "Delete Aircraft";
}

<div class="border mt-4">
    <div class="col-lg-12"><center><h1>@ViewData["Title"]</h1></center></div>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <div class=""><center>Are you sure you want to delete this Aircraft?</center></div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <td><strong>Id</strong></td>
                        <td>@Model.Id</td>
                    </tr>
                    <tr>
                        <td><strong>Name</strong></td>
                        <td>@Model.Name</td>
                    </tr>
                    <tr>
                    <tr>
                        <td><strong>Engine Number</strong></td>
                        <td>@Model.EngineNumber</td>
                    </tr>
                    <tr>
                        <td><strong>Capacity</strong></td>
                        <td>@Model.Capacity</td>
                    </tr>
                    </tbody>
            </table>
            <div class="text-end">
                <form asp-action="Delete">
                    <input type="hidden" name="id" value="@Model.Id" />
                    <button type="submit" class="btn btn-danger">Delete Aircraft</button>
                </form>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

AirlineMS/Views/Aircraft/List.cshtml
@using AirlineMS.Models.Dtos
@model IEnumerable<AircraftDto>
@{
    ViewData["Title"] = "Aircraft List";
}
<div>
    <div class="text-center">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Name</th>
                        <th>Engine Number</th>
                        <th>Capacity</th>
                        <th>Update</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var aircraft in Model)
                    {
                        <tr>
                            <td>@aircraft.Id</td>
                            <td>@aircraft.Name</td>
                            <td>@aircraft.EngineNumber</td>
                            <td>@aircraft.Capacity</td>
                            <td>
                                <a href="#" asp-act>Edit</a>
                            </td>
                            <td>
                                <a href="#">Remove</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-lg-2"></div>
    </div>
</div>

AirlineMS/Views/Aircraft/Update.cshtml
@using AirlineMS.Models.Dtos
@model AircraftDto
@{
    ViewData["Title"] = "Update Aircraft";
}
<div>
    <div class="text-center">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form asp-controller="Aircraft" asp-action="Update" asp-route-agencyId="">
                <div>
                    <label for="">Name</label>
                    <input type="" name="Name" value="@Model.Name"/>
                </div>
                <div>
                    <label for="">Engine Number</label>
                    <input type="" name="EngineNumber" value="@Model.EngineNumber"/>
                </div>
                <div>
                    <label for="">Capacity</label>
                    <input type="" name="Capacity" value="@Model.Capacity"/>
                </div>
                <div>
                    <button class="btn btn-primary">Update Aircraft</button>
                </div>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>