AirlineMS/Models/Entities/Company.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AirlineMS.Models.Entities
{
    public class Company : BaseEntity
    {
        public string Name { get; set; }
        public string CACRegistrationNum { get; set; }
        public string CACDocument { get; set; }
        public string Logo { get; set; }
        public ICollection<Branch> Branches {get; set;} = new HashSet<Branch>();
        public ICollection<Staff> Staffs { get; set; } = new HashSet<Staff>();
        public ICollection<Aircraft> Aircrafts{get; set;} = new HashSet<Aircraft>();
    }
}

AirlineMS/Controllers/BranchController.cs
using AirlineMS.Models.Dtos;
using AirlineMS.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AirlineMS.Controllers
{
    public class BranchController : Controller
    {
        private readonly IBranchService _branchService;

        public BranchController(IBranchService branchService)
        {
            _branchService = branchService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateBranchRequestModel model)
        {
            var response = _branchService.Create(model);
            if (response.Status)
            {
                TempData["Successful"] = " Created Successful";

                return RedirectToAction("List", new {id = response.Data.Id});
            }
            return View();
        }

        [HttpGet]
        public IActionResult CreateHead()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateHead(string id, CreateHeadRequestModel model)
        {
            var response = _branchService.CreateHeadquarters(id, model);
            if (response.Status)
            {
                TempData["Successful"] = " Created Successful";
                return RedirectToAction("List", new {id = id});
            }
            TempData["error"] = response.Message;
            return View();
        }

        [HttpGet]
        public IActionResult Delete(string id)
        {
            // var response = _branchService.Get(id);
            return View();
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult RealDelete(string id)
        {
            var response = _branchService.Delete(id);
            if (response.Status)
            {
                TempData["Successful"] = "Deleted successfully";

                return RedirectToAction("List");
            }
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult List(string id)
        {
            var response = _branchService.GetBranchesByCompanyId(id);
            return View(response.Data);
        }

        [HttpGet]
        public IActionResult Update(string id)
        {
            // var response = _branchService.Get(id);
            return View();
        }

        [HttpPost]
        public IActionResult Update(string id, UpDateBranchRequestModel model)
        {
            var response = _branchService.Update(id, model);
            if (response.Status)
            {
                TempData["Successful"] = " Updated Successful";

                return RedirectToAction("List");
            }
            return View();
        }
    }
}

AirlineMS/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AirlineMS.Models.Dtos;
using AirlineMS.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace AirlineMS.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ILogger<CompanyController> _logger;
        private readonly ICompanyService _companyService;

        public CompanyController(ILogger<CompanyController> logger, ICompanyService companyService)
        {
            _logger = logger;
            _companyService = companyService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(CreateCompanyRequestModel model)
        {
            var result = _companyService.Create(model);
            if (result.Status)
            {
                return RedirectToAction("List");
            }
            return View(result);
        }

        public IActionResult Delete(string id)
        {
            var result = _companyService.Get(id);
            return View(result);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult RealDelete(string id)
        {
            var result = _companyService.Delete(id);
            if (result.Status)
            {
                return RedirectToAction("List");
            }
            return View(result);
        }

        public IActionResult Details(string id)
        {
            var result = _companyService.Get(id);
            return View(result.Data);
        }

        public IActionResult List()
        {
            var result = _companyService.GetAll();
            return View(result.Data);
        }

        public IActionResult Update(string id)
        {
            var result = _companyService.Get(id);
            return View(result);
        }

        [HttpPost]
        public IActionResult Update(string id, UpdateCompanyRequestModel model)
        {
            var result = _companyService.Update(id, model);
            if (result.Status)
            {
                return RedirectToAction("List");
            }
            return View(result);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

AirlineMS/Views/Company/Add.cshtml
@using AirlineMS.Models.Dtos;
@model CompanyDto;
@{
 ViewData["Title"] = "Add Company";
}
<div class="">
    <div class="row">
        <div class="col-md-2 border" style="min-height: 520px; padding: 0px; margin: 0px">
            @await Html.PartialAsync("~/Views/User/Menu.cshtml")
        </div>
        <div class="row col-md-10 pt-3">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <span class="text-center"><h3>@ViewData["Title"]</h3></span>
                <form asp-action="Add" enctype="multipart/form-data">
                    <div>
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" type="text" />
                    </div>
                    <div>
                        <label asp-for="CACRegistrationNum"></label>
                        <input asp-for="CACRegistrationNum" class="form-control" type="text" />
                    </div>
                    <div>
                        <label asp-for="CACDocument"></label>
                        <input asp-for="CACDocument" class="form-control" type="file" />
                        <span asp-validation-for="CACDocument" class="text-danger"></span>
                    </div>
                    <div>
                        <label asp-for="Logo"></label>
                        <input asp-for="Logo" class="form-control" type="file" />
                        <span asp-validation-for="Logo" class="text-danger"></span>
                    </div>
                    <div class="mt-2 text-end">
                        <button type="submit" class="btn btn-primary" style="width: 30%">Add Company</button>
                    </div>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
</div>

AirlineMS/Views/Company/Delete.cshtml
@using AirlineMS.Models.Dtos;
@model CompanyDto;
@{
    ViewData["Title"] = "Delete Company";
}

<div class="border mt-4">
    <div class="col-lg-12"><center><h1>@ViewData["Title"]</h1></center></div>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <div class=""><center>Are you sure you want to delete this Company?</center></div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <td><strong>Id</strong></td>
                        <td>@Model.Id</td>
                    </tr>
                    <tr>
                        <td><strong>Company Name</strong></td>
                        <td>@Model.Name</td>
                    </tr>
                    <tr>
                    <tr>
                        <td><strong>CAC Registration Num</strong></td>
                        <td>@Model.CACRegistrationNum</td>
                    </tr>
                    <tr>
                        <td><strong>CAC Document</strong></td>
                        <td>@Model.CACDocument</td>
                    </tr>
                    <tr>
                        <td><strong>Logo</strong></td>
                        <td>@Model.Logo</td>
                    </tr>
                </tbody>
            </table>
            <div class="text-end">
                <form asp-action="Delete">
                    <input type="hidden" name="id" value="@Model.Id" />
                    <button type="submit" class="btn btn-danger">Delete Company</button>
                </form>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

AirlineMS/Views/Company/Details.cshtml
@model AirlineMS.Models.Dtos.CompanyDto
@{
    ViewData["Title"] = "Company Details";
}
<div class="">
    <div class="row">
        <div class="col-md-2 border" style="min-height: 520px;">
            <h6 class="pt-2" style="">
                <a class="active" asp-action="CreateHead" asp-controller="Branch" asp-route-id="@Model.Id">Create Headquarter</a>
            </h6>
            <h6 class="pt-2">
                <a class="" asp-action="List" asp-controller="Branch" asp-route-id="@Model.Id">Branch List</a>
            </h6>
        </div>
        <div class="row col-md-10 pt-3">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <table class="table">
                    <tr>
                        <td style="width: 50%;"></td>
                        <td class="text-center" style="width: 50%;">
                            <img src="~/Upload/Images/@Model.Logo" height="100" width="100">
                        </td>
                    </tr>
                    <tr>
                        <td>Name</td>
                        <td>
                            @Model.Name
                        </td>
                    </tr>
                    <tr>
                        <td>Registration Number</td>
                        <td>
                            @Model.CACRegistrationNum
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

AirlineMS/Views/Company/List.cshtml
@using AirlineMS.Models.Dtos;
@model IEnumerable<CompanyDto>;
@{
    ViewData["Title"] = "List of Company";
}
<div class="">
    <div class="row">
        <div class="col-md-2 border" style="min-height: 520px; padding: 0px; margin: 0px">
            @await Html.PartialAsync("~/Views/User/Menu.cshtml")
        </div>
        <div class="row col-md-10 pt-3">
            <div class="col-md-12">
                <span class="text-center"><h3>@ViewData["Title"]</h3></span>
                <table class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>CompanyName</th>
                            <th>CACRegistrationNum</th>
                            <th>Add</th>                   
                            <th>Detail</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int SerialNumber = 1;
                            foreach (var company in Model)
                            {
                                <tr>
                                    <td>@SerialNumber</td>
                                    <td>@company.Name</td>
                                    <td>@company.CACRegistrationNum</td>
                                    <td>
                                        <a asp-action="Add" asp-controller="CompanyManager" asp-route-id="@company.Id"> Add Manager</a>
                                    </td>
                                    <td>
                                        <a asp-controller="Company" asp-action="Details" asp-route-id="@company.Id">View</a>
                                    </td>
                                    <td>Remove</td>
                                </tr>
                                SerialNumber++;
                            }
                        }
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

AirlineMS/Views/Company/Update.cshtml
@model AirlineMS.Models.Entities.Company;
@{
    ViewData["Title"] = "Update Company";
}

<div class="border p-3 mt-4">
    <div><h1>@ViewData["Title"]</h1></div>
    <div>
        <form asp-action="Update">
            @* <div>
                <input asp-for="UserId" class="form-control" type="hidden" value="@Model.Id" />
            </div> *@
            <div>
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" type="text" value="@Model.Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="CACRegistrationNum"></label>
                <input asp-for="CACRegistrationNum" class="form-control" type="text" value="@Model.CACRegistrationNum" />
                <span asp-validation-for="CACRegistrationNum" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="CACDocument"></label>
                <input asp-for="CACDocument" class="form-control" type="file" value="@Model.CACDocument" />
                <span asp-validation-for="CACDocument" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Logo"></label>
                <input asp-for="Logo" class="form-control" type="file" value="@Model.Logo" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Branches"></label>
                <input asp-for="Branches" class="form-control" type="number" value="@Model.Branches" />
                <span asp-validation-for="Branches" class="text-danger"></span>
            </div>
            <div class="mt-2 text-end">
                <button type="submit" class="btn btn-primary" style="width: 30%">Update Company</button>
            </div>
        </form>
    </div>
</div>