AirlineMS/Models/Entities/BranchManager.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AirlineMS.Models.Entities
{
    public class BranchManager : BaseEntity
    {
        public string UserId{get; set;}
        public User User{get; set;}
        public string BranchId{get; set;}
        public Branch Branch{get; set;}
    }
}

AirlineMS/Controllers/BranchManagerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AirlineMS.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace AirlineMS.Controllers
{

    public class BranchManagerController : Controller
    {
        private readonly ILogger<BranchManagerController> _logger;
        private readonly IBranchManagerService _branchManagerService;

        public BranchManagerController(ILogger<BranchManagerController> logger, IBranchManagerService branchManagerService)
        {
            _logger = logger;
            _branchManagerService = branchManagerService;
        }

        public IActionResult Index()
        {
            return View();
        }

        /* public IActionResult Create(CreateBranchManagerRequestModel model)
        {
            return View();
        } */

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

AirlineMS/Controllers/FlightController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AirlineMS.Models.Dtos;
using AirlineMS.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AirlineMS.Controllers
{
    public class FlightController : Controller
    {
        private readonly IFlightService _flightService;

        public FlightController(IFlightService FlightService)
        {
            _flightService = FlightService;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(CreateFlightRequestModel model)
        {
            var response = _flightService.Create(model);
            if (response.Status)
            {
                TempData["Successful"] = " Created Successful";

                return RedirectToAction("List");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Delete(string id)
        {
            return View();
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult RealDelete(string id)
        {
          return View();
        }

        [HttpGet]
        public IActionResult List()
        {
            var response = _flightService.GetAll();
            return View(response.Data);
        }

        [HttpGet]
        public IActionResult Update(string id)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Update(string id, UpdateFlightRequestModel model)
        {
            var response = _flightService.Update(id, model);
            if (response.Status)
            {
                TempData["Successful"] = " Updated Successful";

                return RedirectToAction("List");
            }
            return View();
        }

    }
}

AirlineMS/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AirlineMS.Models.Dtos;
using AirlineMS.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace AirlineMS.Controllers
{
    public class StaffController : Controller
    {
        private readonly IStaffService _staffService;
        public StaffController(IStaffService staffService)
        {
            _staffService = staffService;
        }

        [HttpGet, ActionName("List")]
        public IActionResult ListOfStaffsByBranch(string branchId)
        {
           var staffs = _staffService.GetStaffsByBranchId(branchId);
           return View(staffs.Data);
        }
        public IActionResult ListOfStaffsByCompany(string companyId)
        {
           var staffs= _staffService.GetStaffsByCompanyId(companyId);
           return View(staffs.Data);
        }

        public IActionResult Details(string id)
        {
            var staff= _staffService.Get(id);
            return View(staff.Data);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(string branchId, CreateStaffRequestModel model)
        {
            var staff = _staffService.Create(branchId, model);
            if(staff is not null)
            {
                TempData["Exist"] = "Staff created Successfully";
                return RedirectToAction("List");
            }
            return View(); 
        }
        [HttpGet]
        public IActionResult Update(string id)
        {
            var staff = _staffService.Get(id);
            var updateModel  = new UpdateStaffRequestModel
            {
                FirstName = staff.Data.FirstName,
                LastName = staff.Data.LastName,
                PhoneNumber = staff.Data.PhoneNumber

            };
            return View(updateModel);
        }
        [HttpPost]
        public IActionResult Update(string id,UpdateStaffRequestModel model)
        {
            
            _staffService.Update(id,model);
            return RedirectToAction("ListOfStaffsByCompany");
        }
        [HttpGet]
        public IActionResult Delete(string id)
        {
           var staff = _staffService.Get(id);
            return View(staff.Data);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult ActualDelete(string id)
        {
            
            return View();
        }


    }
}

AirlineMS/Views/BranchManager/Index.cshtml
@using AirlineMS.Models.Dtos
@model BranchManagerDto
@{
    ViewData["Title"] = "Branch Manager Dashboard";
}
<div class="pt-4">
    <div class="text-center">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="row container-fluid">
        <div class="col-lg-3 col-md-3 border text-center text-left">
            <div>
                <a href="void:()">Staff Management</a>
                <ul>
                    <li type="circle">
                        <a asp-controller="Staff" asp-action="Add">Add Staff</a>
                    </li>
                    <li type="circle">
                        <a asp-controller="Staff" asp-action="List">Staff List</a>
                    </li>
                </ul>
            </div>
            <div>
                <a href="void:()">Passenger Management</a>
                <ul>
                    <li type="circle">
                        <a asp-controller="Passenger" asp-action="List">Passenger List</a>
                    </li>
                </ul>
            </div>
            <div>
                <a href="void:()">Flight Management</a>
                <ul>
                    <li >
                        <a asp-controller="Flight" asp-action="Add">Add Flight</a>
                    </li>
                    <li type="circle">
                        <a asp-controller="Flight" asp-action="List">Flight List</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-lg-9 col-md-9"></div>
    </div>
</div>